// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gnodi/distro/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MintingAddress        string `protobuf:"bytes,1,opt,name=minting_address,json=mintingAddress,proto3" json:"minting_address,omitempty"`
	ReceivingAddress      string `protobuf:"bytes,2,opt,name=receiving_address,json=receivingAddress,proto3" json:"receiving_address,omitempty"`
	Denom                 string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	MaxSupply             uint64 `protobuf:"varint,4,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	DistributionStartDate string `protobuf:"bytes,5,opt,name=distribution_start_date,json=distributionStartDate,proto3" json:"distribution_start_date,omitempty"`
	MonthsInHalvingPeriod uint64 `protobuf:"varint,6,opt,name=months_in_halving_period,json=monthsInHalvingPeriod,proto3" json:"months_in_halving_period,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a36e9d1654627f0b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMintingAddress() string {
	if m != nil {
		return m.MintingAddress
	}
	return ""
}

func (m *Params) GetReceivingAddress() string {
	if m != nil {
		return m.ReceivingAddress
	}
	return ""
}

func (m *Params) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Params) GetMaxSupply() uint64 {
	if m != nil {
		return m.MaxSupply
	}
	return 0
}

func (m *Params) GetDistributionStartDate() string {
	if m != nil {
		return m.DistributionStartDate
	}
	return ""
}

func (m *Params) GetMonthsInHalvingPeriod() uint64 {
	if m != nil {
		return m.MonthsInHalvingPeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "gnodi.distro.v1.Params")
}

func init() { proto.RegisterFile("gnodi/distro/v1/params.proto", fileDescriptor_a36e9d1654627f0b) }

var fileDescriptor_a36e9d1654627f0b = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0x2a, 0x31,
	0x18, 0x85, 0x19, 0x2e, 0x90, 0xd0, 0xc5, 0xe5, 0x32, 0x81, 0xdc, 0x09, 0xd1, 0x4a, 0xdc, 0x48,
	0x34, 0x4c, 0x43, 0x4c, 0x34, 0x71, 0xa7, 0x31, 0x51, 0x77, 0x04, 0x76, 0x6e, 0x26, 0x85, 0x36,
	0x43, 0x23, 0x6d, 0x27, 0x6d, 0x41, 0x78, 0x05, 0x57, 0x3e, 0x82, 0x0b, 0x1f, 0xc0, 0xc7, 0x70,
	0xc9, 0xd2, 0xa5, 0x81, 0x85, 0x3e, 0x86, 0xe1, 0xaf, 0x18, 0xe2, 0xa6, 0xf9, 0x7b, 0xbe, 0xd3,
	0xd3, 0xf6, 0xa0, 0x9d, 0x54, 0x69, 0x26, 0x08, 0x13, 0xd6, 0x19, 0x4d, 0xa6, 0x1d, 0x92, 0x51,
	0x43, 0xa5, 0x8d, 0x33, 0xa3, 0x9d, 0x0e, 0x2b, 0x40, 0x63, 0x4f, 0xe3, 0x69, 0xa7, 0x51, 0xa5,
	0x52, 0x28, 0x4d, 0x60, 0xf5, 0x9e, 0x46, 0x2d, 0xd5, 0xa9, 0x86, 0x91, 0xac, 0x27, 0xaf, 0xee,
	0x3f, 0xe7, 0x51, 0xa9, 0x0b, 0x51, 0xe1, 0x01, 0xaa, 0x48, 0xa1, 0x9c, 0x50, 0x69, 0x42, 0x19,
	0x33, 0xdc, 0xda, 0x28, 0x68, 0x06, 0xad, 0x72, 0xef, 0xef, 0xb7, 0x7c, 0xee, 0xd5, 0xf0, 0x08,
	0x55, 0x0d, 0x1f, 0x72, 0x31, 0xdd, 0xb6, 0xe6, 0xc1, 0xfa, 0xef, 0x07, 0x6c, 0xcc, 0x35, 0x54,
	0x64, 0x5c, 0x69, 0x19, 0xfd, 0x01, 0x83, 0xdf, 0x84, 0xbb, 0x08, 0x49, 0x3a, 0x4b, 0xec, 0x24,
	0xcb, 0xc6, 0xf3, 0xa8, 0xd0, 0x0c, 0x5a, 0x85, 0x5e, 0x59, 0xd2, 0x59, 0x1f, 0x84, 0xf0, 0x04,
	0xfd, 0x87, 0xbf, 0x88, 0xc1, 0xc4, 0x09, 0xad, 0x12, 0xeb, 0xa8, 0x71, 0x09, 0xa3, 0x8e, 0x47,
	0x45, 0x88, 0xa9, 0x6f, 0xe3, 0xfe, 0x9a, 0x5e, 0x52, 0xc7, 0xc3, 0x53, 0x14, 0x49, 0xad, 0xdc,
	0xc8, 0x26, 0x42, 0x25, 0x23, 0x3a, 0x86, 0x17, 0x66, 0xdc, 0x08, 0xcd, 0xa2, 0x12, 0x5c, 0x52,
	0xf7, 0xfc, 0x46, 0x5d, 0x7b, 0xda, 0x05, 0x78, 0x86, 0x3f, 0x9f, 0xf6, 0x82, 0x87, 0x8f, 0x97,
	0xc3, 0xba, 0xef, 0x79, 0xb6, 0x69, 0xda, 0x77, 0x73, 0x71, 0xf5, 0xba, 0xc4, 0xc1, 0x62, 0x89,
	0x83, 0xf7, 0x25, 0x0e, 0x1e, 0x57, 0x38, 0xb7, 0x58, 0xe1, 0xdc, 0xdb, 0x0a, 0xe7, 0x6e, 0xdb,
	0xa9, 0x70, 0xa3, 0xc9, 0x20, 0x1e, 0x6a, 0x49, 0xe0, 0x6c, 0x5b, 0x71, 0x77, 0xaf, 0xcd, 0x1d,
	0xf9, 0x95, 0xe4, 0xe6, 0x19, 0xb7, 0x83, 0x12, 0xd4, 0x7e, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0x5b, 0xa1, 0x89, 0xd0, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MintingAddress != that1.MintingAddress {
		return false
	}
	if this.ReceivingAddress != that1.ReceivingAddress {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.MaxSupply != that1.MaxSupply {
		return false
	}
	if this.DistributionStartDate != that1.DistributionStartDate {
		return false
	}
	if this.MonthsInHalvingPeriod != that1.MonthsInHalvingPeriod {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MonthsInHalvingPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MonthsInHalvingPeriod))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DistributionStartDate) > 0 {
		i -= len(m.DistributionStartDate)
		copy(dAtA[i:], m.DistributionStartDate)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DistributionStartDate)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MaxSupply != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSupply))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ReceivingAddress) > 0 {
		i -= len(m.ReceivingAddress)
		copy(dAtA[i:], m.ReceivingAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ReceivingAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MintingAddress) > 0 {
		i -= len(m.MintingAddress)
		copy(dAtA[i:], m.MintingAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MintingAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintingAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ReceivingAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxSupply != 0 {
		n += 1 + sovParams(uint64(m.MaxSupply))
	}
	l = len(m.DistributionStartDate)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MonthsInHalvingPeriod != 0 {
		n += 1 + sovParams(uint64(m.MonthsInHalvingPeriod))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			m.MaxSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionStartDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionStartDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonthsInHalvingPeriod", wireType)
			}
			m.MonthsInHalvingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonthsInHalvingPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
